---
apiVersion: v1
kind: Namespace
metadata:
  name: vllm-dist
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-sa
  namespace: vllm-dist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
  namespace: vllm-dist
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vllm
    spec:
      serviceAccountName: vllm-sa
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: vllm
        image: quay.io/dedgar/vllm:v0.0.1
        #image: leseb/vllm-aed8468-with-models
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        command: ["/bin/sh", "-c"]
        args: [
          # actual model path: /root/.cache/huggingface/hub/models--meta-llama--Llama-3.2-1B-Instruct/snapshots/9213176726f574b556790deb
          "vllm serve meta-llama/Llama-3.2-1B-Instruct --ssl-keyfile /etc/ssl/certs/server.key --ssl-certfile /etc/ssl/certs/server.crt --host 0.0.0.0 --port 8000"
        ]
        env:
        # required for offline mode
        - name: TRANSFORMERS_OFFLINE
          value: "1"
        - name: VLLM_CPU_KVCACHE_SPACE
          value: "10"
        - name: VLLM_TARGET_DEVICE
          value: "cpu"
        - name: VLLM_ENFORCE_EAGER
          value: "1"
        - name: VLLM_NO_USAGE_STATS
          value: "1"
        ports:
          - containerPort: 8000
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
          - name: vllm-certs
            mountPath: /etc/ssl/certs
            readOnly: true
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: vllm-certs
        secret:
          secretName: vllm-certs
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-server
  namespace: vllm-dist
spec:
  selector:
    app.kubernetes.io/name: vllm
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
