---
apiVersion: v1
kind: Namespace
metadata:
  name: vllm-dist
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-sa
  namespace: vllm-dist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
  namespace: vllm-dist
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vllm
    spec:
      serviceAccountName: vllm-sa
      containers:
      - name: vllm
        image: quay.io/dedgar/mock-vllm-tls:v0.0.5
        imagePullPolicy: IfNotPresent
        command: ["/app/main"]
        env:
        - name: CERTFILE
          value: "/etc/ssl/certs/server.crt"
        - name: KEYFILE
          value: "/etc/ssl/certs/server.key"
        - name: PORT
          value: "8000"
        - name: MODELNAME
          value: "meta-llama/Llama-3.2-1B-Instruct"
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: vllm-certs
            mountPath: /etc/ssl/certs
            readOnly: true
      volumes:
      - name: vllm-certs
        secret:
          secretName: vllm-certs
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-server
  namespace: vllm-dist
spec:
  selector:
    app.kubernetes.io/name: vllm
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
