---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - deployments
  - persistentvolumes
  - pods
  - pods/exec
  - pods/log
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - '*'
- apiGroups:
  - llamastack.io
  resources:
  - llamastackdistributions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llamastack.io
  resources:
  - llamastackdistributions/finalizers
  verbs:
  - update
- apiGroups:
  - llamastack.io
  resources:
  - llamastackdistributions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
