---
apiVersion: v1
kind: Namespace
metadata:
  name: vllm-dist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
  namespace: vllm-dist
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vllm
    spec:
      containers:
      - name: vllm
        #image: quay.io/dedgar/vllm:v0.0.1
        image: leseb/vllm-aed8468-with-models
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve meta-llama/Llama-3.2-1B-Instruct --ssl-keyfile /etc/ssl/certs/server.key --ssl-certfile /etc/ssl/certs/server.crt --host 0.0.0.0 --port 8000"
        ]
        env:
        #- name: HUGGING_FACE_HUB_TOKEN
        #  valueFrom:
        #    secretKeyRef:
        #      name: hf-token-secret
        #      key: token
        #- name: HF_TOKEN
        #  valueFrom:
        #    secretKeyRef:
        #      name: hf-token-secret
        #      key: token
        - name: VLLM_CPU_KVCACHE_SPACE
          value: "10"
        - name: VLLM_TARGET_DEVICE
          value: "cpu"
        - name: VLLM_ENFORCE_EAGER
          value: "1"
        - name: VLLM_NO_USAGE_STATS
          value: "1"
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: vllm-certs
            mountPath: /etc/ssl/certs
            readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 4Gi
      volumes:
      - name: vllm-certs
        secret:
          secretName: vllm-certs
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-server
  namespace: vllm-dist
spec:
  selector:
    app.kubernetes.io/name: vllm
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: hf-token-secret
#  namespace: vllm-dist
#type: Opaque
#data:
#  # This is a placeholder token for testing - "dummy-token" encoded in base64
#  token: ZHVtbXktdG9rZW4= 