apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- ../default
- ../samples
- ../scorecard

patches:
- path: patches/fips-annotation-patch.yaml
  target:
    group: operators.coreos.com
    version: v1alpha1
    kind: ClusterServiceVersion
